version: "3.1"

services:
  autobot:
    build:
      dockerfile: Dockerfile
      context: .
    image: autobot
    network_mode: host
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "/var/lib/postgres/container/data:/var/lib/postgresql/data"
