version: "3.1"

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    ports:
      - "8080:8080"


  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auto_mention_bot
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"